version: "3"
services:
  pg:
    image: postgres:9.4

  testdb:
    image: postgres:9.3
    environment:
      POSTGRES_PASSWORD: postgres_secret

  conjur:
    build:
      context: ../
      dockerfile: dev/Dockerfile.dev
    image: conjur-dev
    environment:
      CONJUR_APPLIANCE_URL: http://localhost:3000
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_ADMIN_PASSWORD: admin
      CONJUR_ACCOUNT: cucumber
      CONJUR_PASSWORD_ALICE: secret
      CONJUR_DATA_KEY:
      RAILS_ENV:
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
    - ..:/src/conjur-server
    - ../../conjur-policy-parser:/src/conjur-policy-parser
    - authn-local:/run/authn-local
    links:
    - pg:pg
    - ldap-server
    - oidc-keycloak:keycloak

  cucumber:
    image: conjur-dev
    entrypoint: sleep
    command: infinity
    environment:
      LDAP_URI: ldap://ldap-server:389
      LDAP_BASE: dc=conjur,dc=net
      CONJUR_APPLIANCE_URL: http://conjur:3000
      DATABASE_URL: postgres://postgres@pg/postgres
      CONJUR_ADMIN_PASSWORD: admin
      CONJUR_DATA_KEY:
      RAILS_ENV:
    volumes:
      - ..:/src/conjur-server
      - authn-local:/run/authn-local
    links:
      - conjur
      - pg
      - testdb

  client:
    image: conjurinc/cli5
    entrypoint: sleep
    command: infinity
    environment:
      CONJUR_APPLIANCE_URL: http://conjur:3000
      CONJUR_ACCOUNT: cucumber
      CONJUR_AUTHN_LOGIN: admin
    links:
    - conjur:conjur
    volumes:
    - ..:/src/conjur-server

  ldap-server:
    image: osixia/openldap
    command: --copy-service --loglevel debug
    environment:
      LDAP_ORGANISATION: CyberArk
      LDAP_DOMAIN: conjur.net
      LDAP_ADMIN_PASSWORD: ldapsecret

    volumes:
      - ./files/authn-ldap/ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom

  oidc-keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=alice
      - KEYCLOAK_PASSWORD=alice
      - DB_VENDOR=H2
      - CLIENT_ID=conjurClient
      - REDIRECT_URI=http://locallhost.com/
      - CLIENT_SECRET=d7047915-9029-45b8-9bd6-7ec5c2f75e5b
    ports:
      - "7777:8080"

    volumes:
      - ./files/authn-oidc/keycloak/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
      - ./files/authn-oidc/keycloak:/scripts

  oidc-phantomjs:
    environment:
      - KEYCLOAK_USER=alice
      - KEYCLOAK_PASSWORD=alice
      - CLIENT_ID=conjurClient
      - REDIRECT_URI=http://locallhost.com/
      - SCOPE=openid profile
    image: wernight/phantomjs
    entrypoint: sleep
    command: infinity
    volumes:
      - ./files/authn-oidc/phantomjs:/scripts
    links:
      - oidc-keycloak:keycloak

volumes:
  authn-local:
